### ISSUE TITLE
Style/TrailingCommaInLiteral not migrated?

### ISSUE THREAD

**Issue by thomthom** [pocke/mry#33]
I just updated to RuboCop 0.53 and trying this tool for the first time.

I have this config in my `.rubocop.yml`

```yml
Style/TrailingCommaInLiteral:
  Enabled: false
```

I ran `mry .rubocop.yml` (no output from the command).

When I then try to run `rubocop` I get an error:

```
Error: The `Style/TrailingCommaInLiteral` cop no longer exists. Please use `Style/TrailingCommaInArrayLiteral` and/or `Style/TrailingCommaInHashLiteral` instead.
(obsolete configuration found in C:/Users/tthomas2/SourceTree/SUbD/Ruby/.rubocop.yml, please update it)
```

Is this something that `mry` should have migrated?

**Comment by pocke** [comment]
The cop has been separated to two cops. And mry does not have any solution for this case now. Because I just ignored the cop when releasing mry v0.53.0.0.

I think mry should migrate it to the following.


```yaml
# before
Style/TrailingCommaInLiteral:
  Enabled: false

# after
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
```

I would like to support this case.
